# vim: ft=yaml
---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - neofetch

platforms:
  - name: archlinux/archlinux
  - name: bento/debian-9.1
  - name: bento/debian-8.9
  - name: bento/centos-7.3

suites:
  - name: default
  - name: custom
    provisioner:
      pillars-from-files:
        neofetch.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - neofetch
  - name: debug
    provisioner:
      pillars-from-files:
        neofetch.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - neofetch
      log_level: debug
